name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.yml'
    - '**.swift'
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        image: ["swift:5.9", "swift:5.10", "swift:6.0"]

    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        swift build

